[package]
name = "primes-gui"
authors.workspace = true
edition.workspace = true
version = "0.1.1"
description = "A GUI to check the prime factors of a number"
repository.workspace = true
license.workspace = true

[dependencies]
primes = {workspace = true}
eframe = "0.20.1"
