[package]
name = "primes-cli"
authors.workspace = true
edition.workspace = true
version.workspace = true
description = "A CLI program to check the prime factors of a number"
repository.workspace = true
license.workspace = true

[dependencies]
primes = {workspace = true}