[package]
name = "bench"
authors.workspace = true
edition.workspace = true
version.workspace = true
description = "A benchmarking tool for the primes library"
repository.workspace = true
license.workspace = true

[dependencies]
primes = {workspace = true}
num-traits = {workspace = true}